name: Render Quarto PDF

on:
  push:
    paths:
      - "**.qmd"

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"

      - name: Render QMD to PDF
        run: quarto render code.qmd --to pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rendered-pdf
          path: code.pdf
